---
title: Ikigai
timezone: UTC
collections:
  menu:
    title: Menu
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Modern cuisine influenced by Japanese flavors in a lively and fun environment
  right in the heart of downtown Salt Lake City.
baseurl: 
operation: 5-9 tues wed 5-10 thurs-sat
address: 67 W 100 S, Salt Lake City, UT 84101
twitter_username: nakedfishbistro
instagram_username: ikigai_slc
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
about: 'A minimal, Japanese restaurant in the heart of Salt Lake City.

'
image: "/uploads/ikigaiwinter16-6.jpg"
permalink: pretty
