---
title: Ikigai
timezone: UTC
collections:
  menu:
    title: Menu
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: "Lorem Khaled Ipsum is a major key to success. Cloth talk. Surround yourself
  with angels. Another one. I’m up to something. Every chance I get, I water the plants,
  Lion! Put it this way, it took me twenty five years to get these plants, twenty
  five years of blood sweat and tears, and I’m never giving up, I’m just getting started.
  \n\nTo succeed you must believe. When you believe, you will succeed. Cloth talk.
  You do know, you do know that they don’t want you to have lunch. I’m keeping it
  real with you, so what you going do is have lunch. Fan luv.\n\nLorem Khaled Ipsum
  is a major key to success. Cloth talk. Surround yourself with angels. Another one.
  I’m up to something. Every chance I get, I water the plants, Lion! Put it this way,
  it took me twenty five years to get these plants, twenty five years of blood sweat
  and tears, and I’m never giving up, I’m just getting started.\n\nTo succeed you
  must believe. When you believe, you will succeed. Cloth talk. You do know, you do
  know that they don’t want you to have lunch. I’m keeping it real with you, so what
  you going do is have lunch. Fan luv.\n\n"
baseurl: 
operation: 5-9 tues wed 5-10 thurs-sat
address: 67 W 100 S, Salt Lake City, UT 84101
twitter_username: nakedfishbistro
instagram_username: ikigai_slc
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
about: 'A minimal, Japanese restaurant in the heart of Salt Lake City.

'
image: "/uploads/ikigaiwinter16-6.jpg"
permalink: pretty
